### ISSUE TITLE
Optional \drittpruef

### ISSUE THREAD

**Issue by mbanck** [TUM-LIS/tum-dissertation-latex#1]
Not that I'd personally ever need it, but it is my undestanding that some Ph.D. exams have three examiners - when there is a Summa cum Laude in reach I believe. From looking at the source, it seems `tum-dissertation-latex` does not support this.

See e.g. <https://mediatum.ub.tum.de/doc/1360400/1360400.pdf>

**Comment by wallento** [comment]
Thanks for the suggestion! Can you please check the branch `drittpruef` if it fits your needs?

**Comment by mbanck** [comment]
LGTM, besides the nit-pick I mentioned in the comment to the commit.

I can't test-build a PDF though as I don't have access to the myTUM vault.

**Comment by andre-richter** [comment]
You do not have any mytum credentials at all, or access to the logos doesn't work?

For the moment, please comment the sections beneath 
 % FAK logo
and
% TUM logo
in
https://github.com/TUM-LIS/tum-dissertation-latex/blob/master/inc/tumDiss.cls

This should unlock your build.

**Comment by wallento** [comment]
Great, I will merge this one then. Nit-pick adopted in a force push.
