### ISSUE TITLE
Allow draft build without myTUM files

### ISSUE THREAD

**Issue by mbanck** [TUM-LIS/tum-dissertation-latex#3]
It would be nice if one could optionally skip having to download and crop the logos from myTUM and have just a blank square or something.

E.g. while I was at TUM, I haven't managed to get access to myTUM in many years, so can't test-build `tum-dissertation-latex` and it is not trivially obvious what to comment out in order to hack around it.

**Comment by wallento** [comment]
Can you please check this solution?

**Comment by mbanck** [comment]
Works fine, thanks!
