### ISSUE TITLE
German language not working

### ISSUE THREAD

**Issue by theexiile1305** [TUM-LIS/tum-dissertation-latex#8]
I'm trying to use this template with the German language, but it doesn't work like expected. If I execute make on the command line, I get this error:
<img width="793" alt="error" src="https://user-images.githubusercontent.com/24627030/47971792-1876fc00-e095-11e8-9adc-6ab606ca0035.png">

Can you help me out?

**Comment by andre-richter** [comment]
This should be solved by 83cd9d3ad8160a8cdac7db34cfabef21c6cbe5ee.

Please wait ~30minutes until the [Docker container on dockerhub is rebuild](https://hub.docker.com/r/andrerichter/tum-dissertation-latex/builds/), delete your local, checked-out container image and then retry again.

If it solves your issue, please report back.

**Comment by andre-richter** [comment]
Closing for now. Please reopen if issue persists.

Closed by https://github.com/TUM-LIS/tum-dissertation-latex/commit/83cd9d3ad8160a8cdac7db34cfabef21c6cbe5ee
